init:
  - git config --global core.autocrlf input

os:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  - cd build
  - cmake .. -G%GEN%

build:
  project: C:/projects/caches/build/caches.sln

test_script:
  - cmd: ctest -C %CONFIGURATION% -V 
